- name: "Install all packages"
  yum:
    name: "{{packages}}"
    state: present
    
- name: "Start db"
  service:
    name: mariadb
    state: started
    enabled: yes
  
- name: "Start service httpd, if not started"
  service:
    name: httpd
    state: restarted
